### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by h-marvin** [rjblopes/react-native-device-settings#1]
```
.../node_modules/react-native-device-settings/android/src/main/java/com/rjblopes/opensettings/OpenSettingsPackage.java:15: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
```

My project has:
```
"react": "16.0.0-alpha.12",
"react-native": "0.47.1",
```

I did the setup via `npm i react-native-device-settings --save && react-native link react-native-device-settings`.

Everything works well on iOS.

**Comment by adriaandotcom** [comment]
Hi @h-marvin, I created the fix for it in a fork of mine: https://github.com/adriaanvanrossum/react-native-device-settings. PR is waiting here: https://github.com/rjblopes/react-native-device-settings/pull/2/files

**Comment by h-marvin** [comment]
Thank @adriaanvanrossum

**Comment by rjblopes** [comment]
Hi, been working on a different project and forgot to check this repo. Meantime I've merged @adriaanvanrossum  to fix this issue. Thanks.
