### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by cwhenderson20** [rjblopes/react-native-device-settings#6]
Thank you for this library! It's been working great for me. Do you think you could publish a new version of the package on npm that includes the Android `@Override` change from [this commit](https://github.com/rjblopes/react-native-device-settings/commit/64bc34d7fc3d320521000bfe4572eef94887d79b)?

Referencing the git tag does, of course, work, but it's certainly not as clear as using semver.

Thanks again!

**Comment by rjblopes** [comment]
Pushed two new versions: 1.1 with @Override change and 1.2 with additional feature
